apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  backstage.io/kubernetes-id: sample-app2

resources:
#  - project.yaml
#  - rolebindings.yaml
  - sample-app2-deploy.yaml
  - sample-app2-service.yaml
  - sample-app2-route.yaml
